sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "1234"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9Koe3Ra44nHSvXuDrJ
    access-key-secret: DdqYz3pvKXZGC4VbSqNuDw2v1yo0OR
    bucket-name: java-ai-qc
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10
  wechat:
    appid: wx0a8f8ba74a364db3
    secret: 3e085f52d600385dcb08c757c71577dd
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    #privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    #weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: http://635a480f.r34.cpolar.top/notify/payment
    refundNotifyUrl: http://635a480f.r34.cpolar.top/notify/refundSuccess
